# Uncomment the next line to define a global platform for your project
# platform :ios, '14.0'

target 'Example' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Example
  pod 'RobokassaSDK', :git => 'https://github.com/robokassa/sdk-ios.git', :branch => 'main'

end
